<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_TahunMobilImg</name>
   <tag></tag>
   <elementGuidId>4e863d29-65e4-4bfe-903b-06a32c793778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;label_card${j}_mobilBaru&quot;]/descendant::div[@class='year-wrapper-bottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
