<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_unitUcar</name>
   <tag></tag>
   <elementGuidId>0b4eccd9-f038-417d-8bb1-57ad0c109bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;section-katalog&quot;]/div[1]/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div[3]/div/div[1]/div[1]/p/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
