<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Jual_Cepat</name>
   <tag></tag>
   <elementGuidId>6ace3628-e837-4e65-b7e5-75ecff484eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu2']/li/div/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu2 > li.megamenu-content > div.megamenu-item > a > p.first-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>511ba269-b1c6-461b-91a0-e60a331422ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>first-menu</value>
      <webElementGuid>f6077033-f3c8-45c9-ae45-f870fef8dd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jual Cepat</value>
      <webElementGuid>3d0e4924-3eb2-4f1e-befc-800b597092a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/li[@class=&quot;megamenu-content&quot;]/div[@class=&quot;megamenu-item&quot;]/a[1]/p[@class=&quot;first-menu&quot;]</value>
      <webElementGuid>ae60cda5-e8f2-487d-96cf-c89b2b4c2ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu2']/li/div/a/p</value>
      <webElementGuid>bbfbaf8a-14e2-4e82-bab1-ff7ba1359ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[1]/following::p[1]</value>
      <webElementGuid>1f5f1fee-24d6-445a-a86a-9bb304e4c984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra Dealer'])[1]/preceding::p[2]</value>
      <webElementGuid>bef282f2-2d39-4d9b-a253-13d3c1694002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::p[5]</value>
      <webElementGuid>0cf66c08-24c5-4b56-9410-8e3d3449c098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jual Cepat']/parent::*</value>
      <webElementGuid>a45aac30-6add-41fa-adba-5ed09d096549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/div/a/p</value>
      <webElementGuid>3d5325ca-d84c-4f3a-a3bb-9857449595fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Jual Cepat' or . = 'Jual Cepat')]</value>
      <webElementGuid>d2f5c197-eaf6-4875-8ae3-f3b34ac73763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
