<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Masukan_Kilometer</name>
   <tag></tag>
   <elementGuidId>1f2cc789-fd58-4d3e-9e05-023793167871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Masukan Kilometer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ember203</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'harga-jual' and @placeholder = 'Masukan Kilometer' and @id = 'ember203' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af669144-47b1-47d5-8163-e2ac89cf3641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>harga-jual</value>
      <webElementGuid>9ea1aac1-4c81-41a8-ae0c-891467fff60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66d8660c-146b-4d2b-bf68-625bf4bd69f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Kilometer</value>
      <webElementGuid>513bac9b-f5db-4eec-b73f-828c0ef5310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>48a55885-f66d-4f30-8d6c-c9cc196e2280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember203</value>
      <webElementGuid>150911b4-cf08-4464-9f87-4208c44d6de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>harga-jual revamp-input-text-group ember-text-field ember-view</value>
      <webElementGuid>747b2dd1-cc01-4b00-886e-f4697a42b09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58b3605e-fe6f-4997-90f7-194dfd70520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember203&quot;)</value>
      <webElementGuid>aad68390-ee45-485f-ad66-281fb03f5283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ember203']</value>
      <webElementGuid>72d820b2-37cf-4d07-8c28-478837587f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='car-information-form']/div[4]/div[2]/div/input</value>
      <webElementGuid>2c0a929c-562c-42ea-bf65-45c1c3983b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>db8b0b88-7951-4fdc-b16c-227c19a6130f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'harga-jual' and @placeholder = 'Masukan Kilometer' and @id = 'ember203' and @type = 'text']</value>
      <webElementGuid>5be91dcd-1ec2-446f-bef3-ca4ab2b789ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
