<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Submit_img-responsive</name>
   <tag></tag>
   <elementGuidId>9f0c789f-2069-407f-b441-677c3d78d7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trevo-popup']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-center > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac0a3343-6937-4a3c-b474-5cfbc2cf864c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/adirafinance/image/upload/v1698736349/assets/mobil/images/assets/Success_hesrrz.png</value>
      <webElementGuid>ecfec335-92dd-42e6-a134-552ee2e26d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>42f35a49-005c-428d-adfd-9bd9b057db4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>0888168e-2a2a-4a15-9e02-413a33e9b9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trevo-popup&quot;)/div[@class=&quot;modal-dialog feedback-popup modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;flex justify-center&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>c70b848c-266a-487b-b904-208f61153256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trevo-popup']/div/div/div/div/img</value>
      <webElementGuid>e28eee76-db68-4f00-871b-d4cc7152958e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tutup']</value>
      <webElementGuid>3f8caa04-26a2-4c90-a2ab-54ac2e644fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/img</value>
      <webElementGuid>b6ea2901-be7b-447c-9bc1-2e6b9f01b42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/adirafinance/image/upload/v1698736349/assets/mobil/images/assets/Success_hesrrz.png' and @alt = 'Tutup']</value>
      <webElementGuid>76c06325-6bc6-4566-850b-15df28c82f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
