<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phoneNo</name>
   <tag></tag>
   <elementGuidId>6c1dd949-94ff-4c70-9f9b-8851b6b7c603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='outlined-basic'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.css-1v4ccyo > #outlined-basic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fed6dba-f9fc-4f80-bcf5-2d65ccbed6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>681b6785-e8eb-4bc0-b40c-4fabfa82f666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-basic</value>
      <webElementGuid>fe1817d6-d1b2-4f0a-bc1f-b90bcd176faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNo</value>
      <webElementGuid>4f021a6b-326d-48f2-bf5b-519c0c3dfeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor HP</value>
      <webElementGuid>50200192-ca41-4f38-9558-db0506d5f0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb3f4ac0-40a6-4027-8d72-0122335c9d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>2f1db133-87ae-428c-a63c-752ff914878a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konfirmasi-pengajuan-new&quot;)/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg css-wuga8x&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1 css-tuxzvu&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-8 css-fk796o&quot;]/div[@id=&quot;konfirmasi-data-diri&quot;]/div[@class=&quot;section-table&quot;]/section[@class=&quot;MuiBox-root css-lgka67&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-aox3kx&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-lg-6 css-11uz27b&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root css-i44wyl&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl css-1v4ccyo&quot;]/input[@id=&quot;outlined-basic&quot;]</value>
      <webElementGuid>4b91710a-f1c0-4a6f-90f8-861127235b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='outlined-basic'])[3]</value>
      <webElementGuid>69d8e1e9-5874-42db-bce2-90c333c63dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konfirmasi-data-diri']/div/section/div[3]/div/div/div/input</value>
      <webElementGuid>f5e9a753-3831-48e3-be87-ec7c6efbeca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>e31d7b39-5a39-491a-8cef-e56d242b1af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-basic' and @name = 'phoneNo' and @placeholder = 'Nomor HP' and @type = 'text']</value>
      <webElementGuid>ba9c7ab9-6785-41c9-88e2-678aa5786cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
