<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Apakahandayakin</name>
   <tag></tag>
   <elementGuidId>ba2655ed-3cc2-429a-8c7c-3963cf9ac46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='konfirmasi-alert-popup']/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.title-head-alert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>55b45bb0-d9d5-4fd3-b452-eb2680b3a44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-head-alert</value>
      <webElementGuid>39586e0b-6cdb-48b4-b339-a1ac7ecc6374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin ?</value>
      <webElementGuid>d53d9a85-e992-4d23-b45c-85fefaed6d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konfirmasi-alert-popup&quot;)/div[@class=&quot;modal-dialog feedback-popup modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/p[@class=&quot;title-head-alert&quot;]</value>
      <webElementGuid>20604818-5497-4440-a0d6-f38c883139f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konfirmasi-alert-popup']/div/div/div/p</value>
      <webElementGuid>774b7bc5-29c2-4059-afcc-9c73d428566f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      <webElementGuid>cf2333f1-d3e2-4b28-9efb-abc4e29a5969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::p[1]</value>
      <webElementGuid>6ebb1e25-2858-47fb-bfec-cf362890a0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::p[2]</value>
      <webElementGuid>093fa285-9299-4206-94b6-01b0d4680eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[3]/preceding::p[2]</value>
      <webElementGuid>59cc1345-3bb1-46cc-9725-bc10e40f5f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah anda yakin ?']/parent::*</value>
      <webElementGuid>e45982f3-1b51-458f-ab08-554af9c126a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/p</value>
      <webElementGuid>e1560950-7a1c-41b8-9b51-eb55bba4c213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Apakah anda yakin ?' or . = 'Apakah anda yakin ?')]</value>
      <webElementGuid>26aa3607-bb2a-4052-955d-dddec4518f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
