<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AjukanPembiayaan</name>
   <tag></tag>
   <elementGuidId>0eef8501-1245-4669-858b-d4312cfd96a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ajukan_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ajukan_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>244435a5-c115-472f-ae14-6feef4c5c879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajukan_btn</value>
      <webElementGuid>041f31db-effd-4c04-bae7-98e16fd8287d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>edf89dc6-7175-484b-88a0-4291028d576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47415584-0598-4a5d-a47b-80a7b1e32ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ember-action-206</name>
      <type>Main</type>
      <value>206</value>
      <webElementGuid>ed1d3b65-ec96-452f-b27a-a03b4f82c9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajukan Pembiayaan</value>
      <webElementGuid>47f093a8-16de-4f61-8a2c-9b4036565336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajukan_btn&quot;)</value>
      <webElementGuid>5c1c4eba-af42-4455-badc-0ec1d6d57446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ajukan_btn']</value>
      <webElementGuid>cd4a33b3-6688-4cc7-8d7c-d0cc6b9945d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flying-credit']/div/button[2]</value>
      <webElementGuid>2c094766-968a-41ed-8339-29ccc607c657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Kredit'])[1]/following::button[1]</value>
      <webElementGuid>3c0f0ca3-30a8-4693-b1f2-6cebe2b23220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/bulan'])[2]/following::button[2]</value>
      <webElementGuid>a9d36a39-4e32-455b-931c-d9501399b614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil serupa'])[1]/preceding::button[4]</value>
      <webElementGuid>fed74812-ea30-466e-b121-9e1f495685f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua'])[1]/preceding::button[4]</value>
      <webElementGuid>2d87af86-d60f-4c3b-986f-2c6fad257988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajukan Pembiayaan']/parent::*</value>
      <webElementGuid>70a0a6c3-43c3-4d52-8733-2479f6ef9465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button[2]</value>
      <webElementGuid>d3f2b1ac-8680-46e0-800d-e3417ea82420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ajukan_btn' and @type = 'button' and (text() = 'Ajukan Pembiayaan' or . = 'Ajukan Pembiayaan')]</value>
      <webElementGuid>992c872a-9ce8-425c-be36-5d63e59ae01d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
