<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_produkdipilih</name>
   <tag></tag>
   <elementGuidId>7a59cfa3-33ad-48d7-8a4d-823b4187d65d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img_unitCard0']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_unitCard0 > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50afc1a5-7f6a-42bf-9c8d-709d57650b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-mobil-bekas-head&quot;)/div[@class=&quot;MuiContainer-root css-1lcdque-MuiContainer-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1 css-a5rdam-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-8 css-am41oj-MuiGrid-root&quot;]/div[@class=&quot;varian-left&quot;]/div[@class=&quot;hidden-sm hidden-xs visible-lg visible-md&quot;]/div[@id=&quot;productCarouselImage&quot;]/div[@class=&quot;mainSwiper relative&quot;]/div[@id=&quot;img_unitCard0&quot;]/div[1]/div[1]</value>
      <webElementGuid>7534a1e6-4291-458f-b203-b42b492a7ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img_unitCard0']/div/div</value>
      <webElementGuid>a0ce70b3-d603-4497-8622-b2802c35fa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>796a8183-e06f-471c-9156-4ec08343238e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
